'use client';

import React, { useEffect, useRef, useState, useCallback, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import type { VerseSlide } from '../../lib/verseRenderer';

interface BibleVerseData {
  book: string;
  chapter: string;
  verse: string;
  text: string;
  slides?: string[];   // Pre-generated by the Dock — Presentation page consumes, never regenerates
  reference: string;
  slideIndex?: number;
  totalSlides?: number;
}

function PresentationContent() {
  const searchParams = useSearchParams();
  const isPreview = searchParams.get('preview') === 'true'; // ?preview=true displays background
  const isBanner = searchParams.get('banner') === 'true'; // ?banner=true creates 30% height banner

  const [activeVerse, setActiveVerse] = useState<BibleVerseData | null>(null);
  const [currentSlideIndex, setCurrentSlideIndex] = useState<number>(0);
  const [renderedSlides, setRenderedSlides] = useState<VerseSlide[]>([]);
  const [isActive, setIsActive] = useState<boolean>(false);
  const [frameVersion, setFrameVersion] = useState<number>(0);

  const quoteTextRef = useRef<HTMLDivElement>(null);
  const quoteContainerRef = useRef<HTMLDivElement>(null);

  // Latest values for command handlers (avoids stale closures)
  const renderedSlidesRef = useRef<VerseSlide[]>([]);
  const currentSlideIndexRef = useRef<number>(0);

  useEffect(() => {
    renderedSlidesRef.current = renderedSlides;
  }, [renderedSlides]);

  useEffect(() => {
    currentSlideIndexRef.current = currentSlideIndex;
  }, [currentSlideIndex]);

  /**
   * Consume pre-generated slides from the Dock payload.
   * The Presentation page NEVER re-runs the renderer — it only displays
   * slides the Dock has already computed. This keeps generation and display
   * completely separate.
   */
  useEffect(() => {
    if (!activeVerse) return;

    // Use Dock-generated slides if present, otherwise fall back to full text as one slide
    const slideTexts: string[] = activeVerse.slides && activeVerse.slides.length > 0
      ? activeVerse.slides
      : [activeVerse.text];

    const slides: VerseSlide[] = slideTexts.map((text, i) => ({
      text,
      verseNumber: activeVerse.verse,
      slideNumber: i + 1,
      totalSlides: slideTexts.length,
    }));

    const startIndex = Math.min(activeVerse.slideIndex || 0, Math.max(0, slides.length - 1));

    setRenderedSlides(slides);
    setCurrentSlideIndex(startIndex);
    setIsActive(true);

    // Confirm slide info back to Dock
    const payload = {
      action: 'slideInfo',
      data: { totalSlides: slides.length, currentIndex: startIndex },
    };
    const channel = new BroadcastChannel('bible_presentation_channel');
    channel.postMessage(payload);
    localStorage.setItem('biblePresentationCommand', JSON.stringify(payload));
    channel.close();
  }, [activeVerse]);

  // BroadcastChannel and localStorage listeners for instant updates
  useEffect(() => {
    const broadcastSlideChanged = (index: number, total: number) => {
      const payload = {
        action: 'slideChanged',
        data: { index, total },
      };
      const channel = new BroadcastChannel('bible_presentation_channel');
      channel.postMessage(payload);
      localStorage.setItem('biblePresentationCommand', JSON.stringify(payload));
      channel.close();
    };

    const handleCommand = (cmd: { action: string; data: any }) => {
      if (!cmd) return;

      switch (cmd.action) {
        case 'showVerse':
          setActiveVerse(cmd.data);
          break;
        case 'clearDisplay':
          setIsActive(false);
          setCurrentSlideIndex(0);
          setRenderedSlides([]);
          break;
        case 'nextSlide': {
          const slides = renderedSlidesRef.current;
          const idx = currentSlideIndexRef.current;
          if (slides.length > 1 && idx < slides.length - 1) {
            setCurrentSlideIndex(idx + 1);
            broadcastSlideChanged(idx + 1, slides.length);
          }
          break;
        }
        case 'prevSlide': {
          const idx = currentSlideIndexRef.current;
          if (idx > 0) {
            setCurrentSlideIndex(idx - 1);
            broadcastSlideChanged(idx - 1, renderedSlidesRef.current.length);
          }
          break;
        }
        default:
          break;
      }
    };

    // 1. BroadcastChannel listener
    const presentationChannel = new BroadcastChannel('bible_presentation_channel');
    presentationChannel.onmessage = (event) => {
      handleCommand(event.data);
    };

    // 2. LocalStorage storage event listener (fallback)
    const handleStorageChange = (e: StorageEvent) => {
      if (e.key === 'biblePresentationCommand' && e.newValue) {
        try {
          const cmd = JSON.parse(e.newValue);
          handleCommand(cmd);
        } catch (err) {
          console.error('Failed to parse command from localStorage', err);
        }
      }
    };

    window.addEventListener('storage', handleStorageChange);

    // Read initial command state if present
    const initialCmd = localStorage.getItem('biblePresentationCommand');
    if (initialCmd) {
      try {
        const cmd = JSON.parse(initialCmd);
        handleCommand(cmd);
      } catch (e) {}
    }

    return () => {
      presentationChannel.close();
      window.removeEventListener('storage', handleStorageChange);
    };
  }, []);

  // Set the page background class
  useEffect(() => {
    document.body.className = 'overlay-body-transparent';
    return () => {
      document.body.className = '';
    };
  }, []);

  const reference = activeVerse ? `${activeVerse.book} ${activeVerse.chapter}:${activeVerse.verse}` : '';
  const currentSlide = renderedSlides[currentSlideIndex] || null;
  const [dimensions, setDimensions] = useState({ width: 0, height: 0 });

  // Track viewport dimensions (for OBS sizing)
  useEffect(() => {
    const updateDimensions = () => {
      setDimensions({
        width: window.innerWidth,
        height: window.innerHeight
      });
    };
    updateDimensions();
    window.addEventListener('resize', updateDimensions);
    return () => window.removeEventListener('resize', updateDimensions);
  }, []);

  return (
    <div className={`presentation-canvas-container ${isBanner ? 'banner-mode' : ''}`}>
      {/* Dimension display for OBS sizing */}
      <div style={{
        position: 'fixed',
        top: '10px',
        right: '10px',
        background: 'rgba(0, 0, 0, 0.7)',
        color: '#fff',
        padding: '8px 12px',
        borderRadius: '4px',
        fontSize: '14px',
        fontFamily: 'monospace',
        zIndex: 1000,
        pointerEvents: 'none'
      }}>
        {dimensions.width} × {dimensions.height}
      </div>

      {/* Background Image (Rendered only if ?preview=true parameter is set, otherwise transparent for OBS keying) */}
      {isPreview && (
        <>
          <img
            className="presentation-bg-image"
            src="Screenshot 2026-07-21 215142.png"
            alt="Presentation background"
          />
          <div className="presentation-gradient-overlay" />
        </>
      )}

      {/* Lower Third presentation block */}
      <div className={`lower-third ${isActive ? 'active' : ''}`}>
        <div className="overlay-metadata-bar">
          <div className="overlay-year">{reference}</div>
          <div className="overlay-title"></div>
        </div>
        <div className="overlay-quote-container" ref={quoteContainerRef}>
          <div className="overlay-quote-text" ref={quoteTextRef}>
            {currentSlide ? currentSlide.text.replace(/^["']|["']$/g, '') : ''}
          </div>
        </div>
      </div>
    </div>
  );
}

export default function PresentationPage() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <PresentationContent />
    </Suspense>
  );
}
